### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by radnou** [technix/Perl-Analyzer#2]
Hi, 

Could you help me how to use you work ?

I can use the Perl::Analyzer module like this 
`my $pa=Perl::Analyzer->new();
$pa->analyze($dirPath);
$pa->debug();
$pa->to_file($filePath);`

but for the Perl::Analyzer::Output, I don't have any perldoc

**Comment by technix** [comment]
Actually, there is no need to use Perl::Analyzer modules in your own code - the package contains all required scripts to perform analysis.

You need to install the package:
```
perl Makefile.PL
make
make install
```
and then run analyzer executables: 
```
perl-analyzer --source-dir=/your/source/location --datafile=result.dat
perl-analyzer-output --datafile=result.dat --output-dir=./analysis --format=html
```
